site_name: Valheim Discord Connector
repo: https://github.com/nwesterhausen/valheim-discordconnector
theme:
  name: "material"
  locale: "en"
docs_dir: '.'
site_dir: 'dist'
strict: true

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
  - abbr
  - attr_list
  - def_list
  - footnotes
  - codehilite

plugins:
  - search
  - tags
  - git-authors
  - git-revision-date-localized
  - codeinclude
  - markdownextradata
  - img2fig
  - mermaid2
  - awesome-pages
  - navtitles
  - mkdocs_safe_text
  - mkdocs_redirects

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js